In [2]:
import torch

In [4]:
x = torch.tensor([[1., 1.], [2., 2.]], requires_grad=True)
print(x)

tensor([[1., 1.],
        [2., 2.]], requires_grad=True)


In [5]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [6]:
z = y * y * y[0]
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [48., 48.]], grad_fn=<MulBackward0>) tensor(37.5000, grad_fn=<MeanBackward1>)


In [7]:
print(x.grad)
out.backward()
print(x.grad)

None
tensor([[4.5000, 4.5000],
        [6.0000, 6.0000]])


In [43]:
x = torch.randn(3, requires_grad = True)
x

tensor([ 1.6024, -0.6571, -0.6335], requires_grad=True)

In [44]:
y = x * 2
while y.data.norm() < 1000:
    print(y.data.norm())
    print(y.data)
    y = y * 2
print(y)

tensor(3.6882)
tensor([ 3.2048, -1.3143, -1.2669])
tensor(7.3764)
tensor([ 6.4095, -2.6286, -2.5338])
tensor(14.7529)
tensor([12.8191, -5.2571, -5.0676])
tensor(29.5057)
tensor([ 25.6382, -10.5142, -10.1353])
tensor(59.0115)
tensor([ 51.2764, -21.0284, -20.2706])
tensor(118.0230)
tensor([102.5527, -42.0569, -40.5412])
tensor(236.0460)
tensor([205.1055, -84.1137, -81.0824])
tensor(472.0920)
tensor([ 410.2109, -168.2274, -162.1647])
tensor(944.1840)
tensor([ 820.4218, -336.4549, -324.3294])
tensor([1640.8436, -672.9097, -648.6589], grad_fn=<MulBackward0>)


In [45]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
